### ISSUE TITLE
trezor-gpg-agent create crashes

### ISSUE THREAD

**Issue by fruitloop** [romanz/trezor-agent#81] opened 2016-11-25 10:38 UTC
I discovered an error in the `gpg-init` script.

`trezor-gpg-create` keeps crashing.

```
trezor-gpg-create -e "nist256p1" -t my_timestamp -v "Roland Planitz <roland@planitz.at>"
...
2016-11-24 23:27:39,402 INFO         adding nist256p1 GPG subkey for "Roland Planitz <roland@planitz.at>" to existing key                 [__main__.py:38]
2016-11-24 23:27:39,416 INFO         please confirm GPG signature on Trezor for "Roland Planitz <roland@planitz.at>"...                   [client.py:31]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg-create", line 11, in <module>
    load_entry_point('trezor-agent==0.8.0', 'console_scripts', 'trezor-gpg-create')()
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/__main__.py", line 93, in main_create
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/__main__.py", line 50, in run_create
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/encode.py", line 99, in create_subkey
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/protocol.py", line 266, in make_signature
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/keyring.py", line 227, in sign
  File "build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/keyring.py", line 171, in sign_digest
ValueError: ERR
```

best regards
roland

**Comment by romanz** [comment] 2016-11-25 18:57
Please take a look at the latest version on GitHub - the issue seems to be caused by a change I made a month ago (https://github.com/romanz/trezor-agent/commit/1bd6775c35b55aed4187a31d7ac58c7b3587554a), which was causing the trezor-gpg-create to add the TREZOR-based GPG key as a subkey (instead of a primary key, which is probably what most users want).

**Comment by romanz** [comment] 2016-11-25 18:58
GPG key management is hard :(

**Comment by romanz** [comment] 2016-11-26 09:39
Should be fixed now: https://gist.github.com/romanz/a499fe55ff08ba037e26d4cec0e4b78d

**Closed by romanz** 2016-11-26 09:39 UTC
Labels: bug, GPG

**Comment by fruitloop** [comment] 2016-11-26 13:10
It is indeed, thanks a lot
