### ISSUE TITLE
Ubuntu - UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by pruflyos** [romanz/trezor-agent#192] opened 2018-01-21 16:17 UTC
Running `trezor-gpg init` always gives me the followin error:

```
$ trezor-gpg init pruflyos -v
WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:117]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-gpg')()
  File "/home/pruflyos/trezor-agent/agents/trezor/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/__init__.py", line 265, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/__init__.py", line 121, in run_init
    verify_gpg_version()
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/__init__.py", line 85, in verify_gpg_version
    existing_gpg = keyring.gpg_version().decode('ascii')
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 216, in gpg_version
    args = gpg_command(['--version'])
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 200, in gpg_command
    cmd = [get_gnupg_binary()]
  File "/usr/local/lib/python2.7/dist-packages/libagent/util.py", line 211, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 193, in get_gnupg_binary
    return get_gnupg_components(sp=sp)['gpg']
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 185, in get_gnupg_components
    components = dict(re.findall('(.*):.*:(.*)', output.decode('ascii')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

**Comment by romanz** [comment] 2018-01-21 18:38
Thanks for reporting this issue!

**Comment by romanz** [comment] 2018-01-21 18:47
Just to be sure, could you please re-run the following command (and paste the results below)?
```
$ gpgconf --list-components
```

**Comment by pruflyos** [comment] 2018-01-22 00:57
```
$ gpgconf --list-components
gpg:GPG for OpenPGP:/usr/bin/gpg2
gpg-agent:GPG Agent:/usr/bin/gpg-agent
scdaemon:Smartcard Daemon:/usr/lib/gnupg2/scdaemon
gpgsm:GPG for S/MIME:/usr/bin/gpgsm
dirmngr:Key Acquirer:/usr/bin/dirmngr
pinentry:PIN and Passphrase Entry:/usr/bin/pinentry
```

**Comment by pruflyos** [comment] 2018-01-22 00:58
Why did you add the label `Python3`? As you can see in the output of my original post I'm using Python 2.7.

**Comment by romanz** [comment] 2018-01-22 18:18
Could you please try to re-run the initialization command with higher verbosity, on the latest [commit](https://github.com/romanz/trezor-agent/commit/3e67bc9f0e252c175020dc9c9fb1ffccf10a9f9a)?
```
$ trezor-gpg init pruflyos -vv
```

**Comment by pruflyos** [comment] 2018-01-22 20:21
```
$ trezor-gpg init pruflyos -vv
WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:117]
DEBUG        which u'gpgconf' => u'/usr/bin/gpgconf'                                                              [util.py:230]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-gpg')()
  File "/home/pruflyos/trezor-agent/agents/trezor/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/__init__.py", line 265, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/__init__.py", line 121, in run_init
    verify_gpg_version()
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/__init__.py", line 85, in verify_gpg_version
    existing_gpg = keyring.gpg_version().decode('ascii')
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 216, in gpg_version
    args = gpg_command(['--version'])
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 200, in gpg_command
    cmd = [get_gnupg_binary()]
  File "/usr/local/lib/python2.7/dist-packages/libagent/util.py", line 211, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 193, in get_gnupg_binary
    return get_gnupg_components(sp=sp)['gpg']
  File "/usr/local/lib/python2.7/dist-packages/libagent/gpg/keyring.py", line 185, in get_gnupg_components
    components = dict(re.findall('(.*):.*:(.*)', output.decode('ascii')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

**Comment by romanz** [comment] 2018-01-23 18:29
Please update to the latest commit of [trezor-agent](https://github.com/romanz/trezor-agent), since it should log the exact output, causing the issue above:
https://github.com/romanz/trezor-agent/blob/6d8d43db9b23cede846da06f558ffe915d11c502/libagent/gpg/keyring.py#L21

**Comment by pruflyos** [comment] 2018-01-24 10:04
Well I did update to the latest commit and I have that line in `trezor-agent/libagent/gpg/keyring.py`

Here's what I did:
```
$ git pull
Already up-to-date.

$ sudo pip install -e agents/trezor/
Obtaining file:///home/pruflyos/trezor-agent/agents/trezor
Requirement already satisfied: libagent>=0.9.0 in /usr/local/lib/python2.7/dist-packages (from trezor-agent==0.9.0)
Requirement already satisfied: trezor>=0.7.6 in /home/yojoe/src/trezor (from trezor-agent==0.9.0)
Requirement already satisfied: backports.shutil_which>=3.5.1 in /usr/local/lib/python2.7/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.0)
Requirement already satisfied: ConfigArgParse>=0.12.0 in /usr/local/lib/python2.7/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.0)
Requirement already satisfied: ecdsa>=0.13 in /usr/local/lib/python2.7/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.0)
Requirement already satisfied: ed25519>=1.4 in /usr/local/lib/python2.7/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.0)
Requirement already satisfied: pymsgbox>=1.0.6 in /usr/local/lib/python2.7/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.0)
Requirement already satisfied: semver>=2.2 in /usr/local/lib/python2.7/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.0)
Requirement already satisfied: unidecode>=0.4.20 in /usr/local/lib/python2.7/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.0)
Requirement already satisfied: mnemonic>=0.17 in /usr/local/lib/python2.7/dist-packages (from trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: setuptools>=19.0 in /usr/local/lib/python2.7/dist-packages (from trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: requests>=2.4.0 in /usr/local/lib/python2.7/dist-packages (from trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: click>=6.2 in /usr/local/lib/python2.7/dist-packages (from trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: pyblake2>=0.9.3 in /usr/local/lib/python2.7/dist-packages (from trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: hidapi>=0.7.99.post20 in /usr/local/lib/python2.7/dist-packages (from trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python2.7/dist-packages (from mnemonic>=0.17->trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor>=0.7.6->trezor-agent==0.9.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor>=0.7.6->trezor-agent==0.9.0)
Installing collected packages: trezor-agent
  Found existing installation: trezor-agent 0.9.0
    Uninstalling trezor-agent-0.9.0:
      Successfully uninstalled trezor-agent-0.9.0
  Running setup.py develop for trezor-agent
Successfully installed trezor-agent
```

**Comment by rasom** [comment] 2018-01-30 11:36
I'm experiencing the same issue on macos, and it can be fixed by replacing `ascii ` with `utf-8` at this line
https://github.com/romanz/trezor-agent/blob/master/libagent/gpg/keyring.py#L195

In my case `output` contains Cyrillic chars so probably that's the reason of the issue. 
```
gpg:OpenPGP:/usr/local/Cellar/gnupg/2.2.4/bin/gpg
gpg-agent:Закриті ключі:/usr/local/Cellar/gnupg/2.2.4/bin/gpg-agent
scdaemon:Картки пам’яті:/usr/local/Cellar/gnupg/2.2.4/libexec/scdaemon
gpgsm:S/MIME:/usr/local/Cellar/gnupg/2.2.4/bin/gpgsm
dirmngr:Мережа:/usr/local/Cellar/gnupg/2.2.4/bin/dirmngr
pinentry:Введення пароля:/usr/local/opt/pinentry/bin/pinentry
```

**Comment by romanz** [comment] 2018-01-30 18:19
Thanks @rasom!
The commit above should fix the issue :)

**Comment by rasom** [comment] 2018-01-31 14:54
Thanks @romanz, I can't reproduce issue anymore.

**Closed** 2018-01-31 16:01 UTC
