### ISSUE TITLE
signing failed: communication with agent failed

### ISSUE THREAD

**Issue by NTICompass** [romanz/trezor-agent#242] opened 2018-05-10 23:46 UTC
I have a KeepKey and when I run `keepkey-agent user@server`, I get asked to enter my PIN and then I am given a public key.

Then, then I try to connect via SSH using `keepkey-agent -c user@server`, I get an error.  I am asked for my PIN, but then all I see is:

```
sign_and_send_pubkey: signing failed: communication with agent failed
2018-05-10 19:45:47,744 WARNING      error: KeepKey error: (1, 'Unknown message')                                                         [server.py:63]
Traceback (most recent call last):
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/device/trezor.py", line 151, in sign
    ecdsa_curve_name=curve_name)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 135, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 690, in sign_identity
    return self.call(proto.SignIdentity(identity=identity, challenge_hidden=challenge_hidden, challenge_visual=challenge_visual, ecdsa_curve_name=ecdsa_curve_name))
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 148, in wrapped_f
    return f(*args, **kwargs)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 189, in call
    msg = handler(resp)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/keepkeylib/client.py", line 201, in callback_Failure
    raise CallException(msg.code, msg.message)
keepkeylib.client.CallException: (1, 'Unknown message')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/ssh/protocol.py", line 144, in sign_message
    signature = self.conn.sign(blob=blob, identity=key['identity'])
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/ssh/__init__.py", line 213, in sign
    return conn.sign_ssh_challenge(blob=blob, identity=identity)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/ssh/client.py", line 49, in sign_ssh_challenge
    return self.device.sign(blob=blob, identity=identity)
  File "/home/nticompass/.local/lib64/python3.5/site-packages/libagent/device/trezor.py", line 159, in sign
    raise interface.DeviceError(msg)
libagent.device.interface.DeviceError: KeepKey error: (1, 'Unknown message')
```

**Comment by romanz** [comment] 2018-05-12 18:34
Thanks for reporting this issue!
Please let me know which Keepkey firmware are you using, so I could reproduce this issue on my device.

**Comment by NTICompass** [comment] 2018-05-13 04:04
I was originally running the 5.1 firmware (the latest stable).  I contacted KeepKey themselves and they suggested I try their beta client/firmware.

https://chrome.google.com/webstore/detail/keepkey-client-rc/ndpjhnboalogfiafbknodggihfiedibo this is the beta client and will update the firmware to 5.2

That's what I'm using now, but am still getting this same error when trying to use SSH

**Comment by romanz** [comment] 2018-05-13 08:16
Using a older version of the firmware seems to work (without PIN protection):
```
$ keepkeyctl get_features
vendor: "keepkey.com"
major_version: 3
minor_version: 0
patch_version: 17
<snip>
$ pip3 install --user -e agents/keepkey
<snip>
Successfully installed ConfigArgParse-0.13.0 backports.shutil-which-3.5.1 docutils-0.14 ecdsa-0.13 ed25519-1.4 hidapi-0.7.99.post21 keepkey-4.0.2 keepkey-agent libagent-0.11.2 lockfile-0.12.2 mnemonic-0.18 pbkdf2-1.3 protobuf-3.5.2.post1 pymsgbox-1.0.6 python-daemon-2.1.2 semver-2.7.9 setuptools-39.1.0 six-1.11.0 unidecode-1.0.22
$ keepkey-agent localhost -e nist256p1 >> ~/.ssh/authorized_keys 
$ keepkey-agent localhost -e nist256p1 -cv
2018-05-13 11:15:13,836 INFO         identity #0: <ssh://localhost|nist256p1>                                                             [__init__.py:251]
2018-05-13 11:15:13,838 INFO         using [b'ttyname=/dev/pts/0', b'display=:0.0'] for pinentry options                                  [ui.py:67]
2018-05-13 11:15:13,841 INFO         running ['ssh', 'localhost'] with {'SSH_AUTH_SOCK': '/tmp/trezor-ssh-agent-87q_9g30', 'SSH_AGENT_PID': '3899'} [server.py:119]
2018-05-13 11:15:14,033 INFO         please confirm user "roman" login to "<ssh://localhost|nist256p1>" using KeepKey...                  [client.py:46]
2018-05-13 11:15:17,730 INFO         signature status: OK                                                                                 [protocol.py:151]
Welcome to Ubuntu 17.10
```

**Comment by romanz** [comment] 2018-05-13 08:34
Also works on 4.0.0 version:
```
$ keepkeyctl get_features | head
vendor: "keepkey.com"
major_version: 4
minor_version: 0
patch_version: 0
<snip>
$ keepkey-agent localhost -e nist256p1 -cv
2018-05-13 11:33:20,273 INFO         identity #0: <ssh://localhost|nist256p1>                                                             [__init__.py:251]
2018-05-13 11:33:20,275 INFO         using [b'ttyname=/dev/pts/0', b'display=:0.0'] for pinentry options                                  [ui.py:67]
2018-05-13 11:33:20,278 INFO         running ['ssh', 'localhost'] with {'SSH_AUTH_SOCK': '/tmp/trezor-ssh-agent-_24wqsun', 'SSH_AGENT_PID': '5445'} [server.py:119]
2018-05-13 11:33:26,420 INFO         please confirm user "roman" login to "<ssh://localhost|nist256p1>" using KeepKey...                  [client.py:46]
2018-05-13 11:33:29,198 INFO         signature status: OK                                                                                 [protocol.py:151]
Welcome to Ubuntu 17.10 <snip>
```

**Comment by romanz** [comment] 2018-05-13 08:39
Could you please re-run the connection command with higher verbosity, so we could see what is causes the error?
```
$ keepkey-agent -vv -c user@server
```

**Comment by romanz** [comment] 2018-05-13 08:54
After trying a few more versions - the issue doesn't appear at v4.0.3, but does happen at v5.0.1.

**Comment by romanz** [comment] 2018-05-13 09:02
@bgok @keepkeyjon Could you please take a look?

**Comment by NTICompass** [comment] 2018-05-13 15:39
Looks like something in a firmware update is the problem.  I had emailed KeepKey about this issue, so maybe I can point this out to them.

**Comment by keepkeyjon** [comment] 2018-05-14 22:45
The `SignIdentity` message got [removed](https://github.com/keepkey/keepkey-firmware/commit/3adcaf024b0c9542ff962c003bfd7eb617b63a09) in an overabundance of caution during our response to the [sprintf disclosure](https://www.keepkey.com/2018/03/09/security-updates-responsible-disclosure/). Since handling that message involves a lot of string processing, it seemed prudent to pull it temporarily while we re-evaluated the security of it... sorry that it broke things for you.

We plan on adding it back soon... I'll update this thread when we've published the firmware with the fix.

**Comment by NTICompass** [comment] 2018-05-15 01:08
@keepkeyjon Thanks for the info.

**Comment by romanz** [comment] 2018-05-18 06:47
Thanks for the update!
Closing the issue for now.

**Closed by romanz** 2018-05-18 06:47 UTC
Labels: bug, help wanted, keepkey

**Comment by keepkeyjon** [comment] 2018-05-24 00:29
@NTICompass  This firmware has the `SignIdentity` message added back: https://github.com/keepkey/keepkey-firmware/releases/tag/v5.4.1 You can either upload it yourself with `keepkeyctl`, or find it in the beta release here: https://chrome.google.com/webstore/detail/keepkey-client-rc/ndpjhnboalogfiafbknodggihfiedibo

**Comment by NTICompass** [comment] 2018-05-24 04:13
@keepkeyjon I updated my KeepKey to 5.4.1 and SSH works!  Thanks a lot! :-D
