### ISSUE TITLE
Trezor T asks two times for the passphrase

### ISSUE THREAD

**Issue by JediWed** [romanz/trezor-agent#225] opened 2018-03-27 07:48 UTC
When trying to connect via trezor-agent user@host -c Trezor T asks for a passphrase,
after that it asks if you want to sign login of user@host and asks again for a passphrase.
That can be very annoying and I don't understand the reason for asking two times.

OS: macOS High Sierra
Agent: trezor-agent=0.9.2 libagent=0.11.2
Trezor T: 2.0.6

**Comment by romanz** [comment] 2018-03-27 11:13
Thanks for reporting this issue!

In TREZOR 1, I was caching the passphrase at the client code:
https://github.com/romanz/trezor-agent/blob/5efb752979288f5f452cf7304d619549ea059488/libagent/device/trezor.py#L49

In Trezor T, if you can use the device to enter the passphrase - it seems that the passphrase is not being cached between the public key derivate (1st prompt) and the signature (2nd prompt).

Will take a look to understand the issue better.

**Comment by romanz** [comment] 2018-03-27 12:55
We need to pass the `state` correctly during initialization:
https://github.com/trezor/trezor-core/blob/25ae6bba5168d46d6bb8354ecd9cffb3fc80180b/src/apps/homescreen/__init__.py#L14

**Comment by romanz** [comment] 2018-03-28 13:38
Should be fixed at the latest Git versions https://github.com/trezor/python-trezor/commit/bd3d014dd4b2e9c22d15e12273ebfd488edccc8e and https://github.com/romanz/trezor-agent/commit/7443fc651211a6b7ccb6be6bc62ecb6f11a85a6e.
Please take a look :)

**Comment by JediWed** [comment] 2018-03-28 17:21
Just pip install --upgrade trezor-agent?

**Comment by romanz** [comment] 2018-03-28 17:22
It's not released yet, so please use:
```
$ pip install git+https://github.com/romanz/trezor-agent
```

**Comment by JediWed** [comment] 2018-03-28 17:58
Still asks two times for the passphrase :(

**Comment by romanz** [comment] 2018-03-28 18:52
This is indeed weird...
Could you please run `trezor-agent -vv user@host -c` and attach the log?
It should contain a `caching state from` line:
https://github.com/romanz/trezor-agent/blob/master/libagent/device/trezor.py#L83

**Comment by JediWed** [comment] 2018-03-28 19:13
[trezor-agent.log](https://github.com/romanz/trezor-agent/files/1857371/trezor-agent.log)

Replaced my user and host by user@host.tld

**Comment by romanz** [comment] 2018-03-28 19:41
It seems that you are using TREZOR Bridge:
```
2018-03-28 21:11:48,803 DEBUG        http://127.0.0.1:21325 "POST /acquire/web02/null HTTP/1.1" 200 18                                    [connectionpool.py:396]
2018-03-28 21:11:49,113 DEBUG        http://127.0.0.1:21325 "POST /call/101 HTTP/1.1" 200 16                                              [connectionpool.py:396]
2018-03-28 21:11:50,534 DEBUG        http://127.0.0.1:21325 "POST /call/101 HTTP/1.1" 200 16                                              [connectionpool.py:396]
2018-03-28 21:11:55,433 DEBUG        http://127.0.0.1:21325 "POST /call/101 HTTP/1.1" 200 144                                             [connectionpool.py:396]
2018-03-28 21:11:55,433 DEBUG        caching state from <PassphraseStateRequest: {'state': bytearray(b"\xcdz\x8c:\x07\xa2\xb1\x97\xed\xe1\xc1L3\x88\xdb\xc5\xcf\xd4\x14\x99\xde\xe6\xb1\'\x067\xa2[I\xd7\xdc\x11)\x8e<\xa2I\xe4*\x9a\x85\xc1^\xcb\xf2\x06\x98\xbd\x0fFXJ\x83\xef\x9e\xc5\xe0\xdb\xb7\xbf<}P\x9b")}> [trezor.py:83]
2018-03-28 21:11:56,252 DEBUG        http://127.0.0.1:21325 "POST /call/101 HTTP/1.1" 200 406                                             [connectionpool.py:396]
2018-03-28 21:11:56,254 DEBUG        http://127.0.0.1:21325 "POST /release/101 HTTP/1.1" 200 18                                           [connectionpool.py:396]
```
I guess that the `state` may be dropped there...
Will take a look at it in the following days.

**Comment by JediWed** [comment] 2018-03-28 19:43
Great, thanks!

**Comment by romanz** [comment] 2018-03-29 19:57
I've built the latest TREZOR daemon (aka Bridge), and it seems to work as intended (asks for passphrase once), so it seems that the `state` is forwarded correctly to the device.
Could you please update to the latest version from https://github.com/trezor/trezord-go?

BTW, does this also happens when running without a Bridige (i.e. when the communication happens directly via USB HID)?

**Comment by romanz** [comment] 2018-04-05 09:40
@JediWed Sorry for the delayed response...
Could you please attach the log for the WebUsbTransport case (i.e. when running without `trezord`)?

**Comment by romanz** [comment] 2018-04-25 08:30
Ping :)

**Comment by JediWed** [comment] 2018-04-25 08:38
I'm very sorry. I was very busy the last few weeks. I will have a look this evening.

**Comment by romanz** [comment] 2018-04-25 09:14
No worries, I was just curios :)

**Comment by romanz** [comment] 2018-05-04 05:53
Please re-open if it still happens.

**Closed by romanz** 2018-05-04 05:53 UTC
Labels: bug, trezor-model-T
