### ISSUE TITLE
Pinentry with trezor

### ISSUE THREAD

**Issue by Dehumanizer77** [romanz/trezor-agent#475] opened 2024-01-17 11:37 UTC
I'm not entirely sure if this is a bug or a feature, but when I need to enter the passphrase on Trezor, I always need to enter it on the trezor itself. Shouldn't I be able to enter it using pinentry on the computer? I have pinentry installed and trezor-gpg-agent runs with --passphrase-entry-binary=pinentry ...

**Comment by doolio** [comment] 2024-04-05 18:00
Duplicate of #325? If you agree consider closing this issue.

**Comment by Dehumanizer77** [comment] 2024-04-05 18:03
Yes it appears so. But it seems that it's not going to be resolved anytime soon, if it's open for 3 years now :-)

**Comment by doolio** [comment] 2024-04-05 20:14
Well, I think the point about entering the pin on the trezor-T was answered by 

> Since Trezor model T supports on-device PIN entry, you shouldn't get notified to entry the PIN on your host machine.

That issue remains open as there are some unanswered follow up questions.

**Closed** 2024-04-05 20:24 UTC
