### ISSUE TITLE
"No secret key" GPG error on Arch Linux with Nano S

### ISSUE THREAD

**Issue by markasoftware** [romanz/trezor-agent#168] opened 2017-11-15 02:17 UTC
https://asciinema.org/a/Vtk29mWoAlqeBvH6aXTDxpceO

It seems almost identical to #117. It seems to fail before any log file is created.

Output of `gpg2 --version | head -n1` is `gpg (GnuPG) 2.2.2`, which is later than in #117 (another day of Arch Linux, another broken update).

Output of `gpgconf --list-dirs`: http://sprunge.us/OBLF
Output of `gpg2 --export | gpg2 --list-packets`: http://sprunge.us/ZefR

I can provide whatever info you need. Thanks!

**Comment by romanz** [comment] 2017-11-15 06:28
Thanks for reporting this issue!

**Comment by markasoftware** [comment] 2017-11-15 15:01
`ledger-gpg init -vv "mark"`: http://sprunge.us/QCKY

**Comment by romanz** [comment] 2017-11-15 18:55
It seems that `ledger-gpg-agent` is not working as intended (following the `No secret key` error).
Could you please upload its log (it should be stored under `~/.gnupg/ledger/gpg-agent.log`)?

**Comment by markasoftware** [comment] 2017-11-15 21:57
No `gpg-agent.log` exists, it seems like it fails before the log file is created.

I have this error on multiple Arch machines, both with same version of gpg (2.2.2). I'll be able to test this with older versions of GPG and different distros later today.

**Comment by markasoftware** [comment] 2017-11-15 23:51
I have tested it in a lubuntu VM with gpg 2.1.15 and it works fine. However, in Arch, when I use gpg 2.1.15-2 from https://archive.archlinux.org/, it still doesn't work, although I get a different error now...Output of `ledger-gpg init 'test'` with gpg 2.1.15-2 on Arch: http://sprunge.us/WVTM

One other thing I noticed is that when generating the key on lubuntu, it asked me to "sign" on the ledger one additional time than it did with gpg 2.2.2 on Arch.

**Comment by romanz** [comment] 2017-11-16 20:20
> No gpg-agent.log exists, it seems like it fails before the log file is created.

Could you please try to start the `ledger-gpg-agent` from command-line, using:
```
$ export GNUPGHOME=${HOME}/.gnupg/ledger
$ ledger-gpg-agent &
$ gpg2 -K
```

The `ledger-gpg-agent` runs with high verbosity logging, so if it fails to start - we should see why.

**Comment by markasoftware** [comment] 2017-11-16 23:15
Ok, finally something worked! This is super weird...https://asciinema.org/a/rJ0h0FO27gowakSdXBU3YWWnB

So, after running `ledger-gpg init` but before doing anything else, `ledger-gpg-agent` needs to be started at least once. Then, even if it is killed (and no longer shows up in `ps aux`), it will function afterwards. So, now I know how to workaround the issue, but it still could be fixed. Maybe `ledger-gpg-agent` could be automatically run at the end of `ledger-gpg init`?

**Comment by romanz** [comment] 2017-11-17 08:49
Could you please try the [latest version](https://github.com/romanz/trezor-agent/commits/master) of `trezor-agent`?
I have merged a few fixes yesterday, which may be relevant to this issue.

Also, does this issue reproduces with `fake-device-agent`? 
It can be installed using:
```
$ pip install agents/fake
$ fake-device-gpg init "Foobar" -vv
$ export GNUPGHOME=/home/roman/.gnupg/fake-device
$ gpg2 -K --debug-all
```
The `--debug-all` flag can be useful to debug `gpg-agent`-related issues...

**Comment by romanz** [comment] 2017-12-08 18:25
Ping :)

**Comment by xaionaro** [comment] 2018-06-04 12:36
I have the same issue with trezor:
```
gpg: Warning: not using 'Dmitry Yu Okunev <xaionaro@gmail.com>' as default key: No secret key
gpg: all values passed to '--default-key' ignored
gpg: keydb_search failed: Broken pipe
gpg: no default secret key: Broken pipe
gpg: signing failed: Broken pipe
```

**Comment by romanz** [comment] 2018-06-04 20:20
Thanks for reporting this issue!
Which OS and GnuPG versions are you using?
Could you please attach `~/.gnupg/trezor/gpg-agent.log`?

**Comment by markasoftware** [comment] 2018-06-04 20:24
Hard to say for sure but this looks like it is a different problem than mine because of the broken pipe errors.

**Comment by xaionaro** [comment] 2018-06-05 11:13
@romanz 
The problem disappeared after I installed the recent `trezor-agent` (directly from GitHub) and added `export $(dbus-launch)` to my bashrc.

**Comment by romanz** [comment] 2018-06-05 18:02
Good to hear, thanks for the update :)

**Closed by romanz** 2018-06-05 18:02 UTC
Labels: Arch, GPG, bug, installation, no reply

**Comment by korzq** [comment] 2018-11-23 00:49
macOS - mojave - pip - trezor

same problem. Can be resolved by doing `gpg2 -K` on startup.

**Comment by romanz** [comment] 2018-11-23 07:53
which gpg version are you running?
