### ISSUE TITLE
trezor-agent startup error

### ISSUE THREAD

**Issue by bscarvell** [romanz/trezor-agent#85] opened 2016-12-06 04:47 UTC
Hey romanz,

Hope you can push me in the right direction. I followed your instructions on the README page and I keep getting the following when launching trezor-agent:

```
$ trezor-agent
Traceback (most recent call last):
  File "/usr/bin/trezor-agent", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3013, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2999, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3026, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (hidapi 0.7.99.post20 (/usr/lib64/python2.7/site-packages), Requirement.parse('hidapi==0.7.99.post15'), set(['keepkey']))
```

Any ideas on how to fix this?

**Comment by romanz** [comment] 2016-12-06 08:10
Thanks for trying this tool and for reporting this issue!
This should be resolved by https://github.com/keepkey/python-keepkey/pull/8 but meanwhile, I'll update `setup.py` to use the common version of `hidapi` to make it work as intended.

**Comment by romanz** [comment] 2016-12-06 08:21
The fix is pushed also to [PyPI](https://pypi.python.org/pypi/trezor_agent/0.8.1).

**Closed by romanz** 2016-12-06 08:21 UTC
